# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfdb22310e67da4581b323ba59baae034d3f6b5586d07a0361d07ac4d108f2bcbcbc4408400720823d902b29f769f5aa7c090d4b4750a6dc8a07c2f176019756

test:
  secret_key_base: 16e92a96552c2b719e7244a9e14a58e13e139e80b2dcf85e6c7527144056f59095719062e96806f9cb6541004990500f2fb034ca4ad628799bc6b26f1c1c6917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
